name: StormBreaker Kernel Build

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-24.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
        bc \
        bison \
        flex \
        cpio \
        curl \
        git \
        wget \
        zip \
        unzip \
        xxd \
        python3 \
        llvm \
        clang \
        lld \
        binutils-aarch64-linux-gnu

    - name: Build Python2
      run: |
       sudo apt install -y build-essential wget zlib1g-dev libssl-dev libffi-dev

       wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
       tar xf Python-2.7.18.tgz
       cd Python-2.7.18

       ./configure --prefix=/usr/local/python2
       make -j$(nproc)
       sudo make install

       sudo ln -sf /usr/local/python2/bin/python2.7 /usr/local/bin/python2
      
    - name: Setup git
      run: |
        git config --global user.name "Forenche"
        git config --global user.email "prahul2003@gmail.com"
        git config --global color.ui false

    - name: Install Python2 fallback
      run: |
        sudo ln -sf /usr/bin/python2 /usr/bin/python || true

    - name: Build Kernel
      env:
        TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: |
        chmod +x kramel.sh
        bash kramel.sh

    - name: Upload Kernel ZIP
      uses: actions/upload-artifact@v4
      with:
        name: StormBreaker-Kernel
        path: |
          AnyKernel3/*.zip
